apiVersion: apps/v1
kind: Deployment
metadata:
  name: twittor-app-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twittor-app
  template:
    metadata:
      labels:
        app: twittor-app
    spec:
      containers:
      - name: twittor-app
        image: bigegi84/twittor-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: twittor-app-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: twittor-app
  ports:
  - name: twittor-app
    protocol: TCP
    port: 80
    targetPort: 80