apiVersion: apps/v1
kind: Deployment
metadata:
  name: twittor-graphql-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twittor-graphql
  template:
    metadata:
      labels:
        app: twittor-graphql
    spec:
      containers:
      - name: twittor-graphql
        image: bigegi84/twittor-graphql:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: twittor-graphql-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: twittor-graphql
  ports:
  - name: twittor-graphql
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: twittor-graphql-srv
spec:
  type: NodePort
  selector:
    app: twittor-graphql
  ports:
  - name: twittor-graphql
    protocol: TCP
    port: 80
    targetPort: 80